In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [9]:
##reshape
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
r=a.reshape(2,3)
print(r)

b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
res = b.reshape(3, -1)
print(res)
##Explanation: b.reshape(3, -1)
#tells NumPy to create 3 rows, and it computes the remaining dimension as 4 columns, since 12 ÷ 3 = 4.

[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
##arange
##a = np.arange(5) creates a 1D NumPy array:
##array([0, 1, 2, 3, 4])
import numpy as np

a = np.arange(1, 10)
b = a.reshape(3,3)
print(a)
print(b)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
##Find sum of all elements
arr = np.array([5, 10, 15])
print(np.sum(arr))


30


In [18]:
##Find mean
arr1 = [20, 2, 7, 1, 34]
print(np.mean(arr1))

arr2 = [[14, 17, 12],
       [15,  6, 27],
       [23,  2, 54]]

print(np.mean(arr2))           # entire array
print(np.mean(arr2, axis=0))   # column-wise mean
print(np.mean(arr2, axis=1))   # row-wise mea

12.8
18.88888888888889
[17.33333333  8.33333333 31.        ]
[14.33333333 16.         26.33333333]


In [21]:
##Create:
##3x3 zero matrix
arr3=np.zeros((3,3))
print(arr3)
##2x2 ones matrix
arr4=np.ones((2,2))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
